#!/usr/bin/env python
from gui.mainwindow import MainWindow
from gi.repository import Gtk
from tools import constants
import os

if not os.path.isdir(constants.NOTES_DIR):
    os.mkdir(constants.NOTES_DIR)
if not os.path.isdir(os.path.join(constants.NOTES_DIR, "dist")):
    pass #Copy the bootstrap files
mainWindow = MainWindow()
Gtk.main()
